--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/buchwasa/UHCGames
build-by-default: true
branches:
- main
projects:
  UHCGames:
    path: ""
    libs:
      - src: stephen-mc-pl/libChunkLoader/libChunkLoader
        branch: pm4
        version: 3.0.0
    lint:
      phpstan: false
...
